#!/usr/bin/python3

import argparse
import requests
import json
import pprint
import subprocess
import re
import logging
import jinja2

logging.basicConfig(level=logging.INFO)

CVEURL = "https://cve.mitre.org/cgi-bin/cvename.cgi?name=%s"
url = "https://cve.circl.lu/api/last"
pp = pprint.PrettyPrinter()
result = {}

def genPkgIndex():
    # Fetch all packages installed on this system
    logging.debug("Building Package Index...")
    return subprocess.check_output(["dpkg-query", "-W", "-f=${Package}:${Version}\n"]).decode('utf-8').strip().split('\n')

def scanCVE(index, vuln, verbose):
    logging.debug("Scanning for %s" % (vuln["id"]))
    affected_packages = []
    for package in vuln["vulnerable_product"]:
        p = package.split(":")
        pkg = re.compile(p[4] + "*")
        r = list(filter(pkg.match, index))
        if len(r) > 0:
            for item in r:
                if item not in affected_packages:
                    affected_packages.append(item)
    if len(affected_packages) > 0:
        result[vuln["id"]] = {"status": "Failed", "packages": affected_packages, "url": CVEURL % vuln["id"]}
    else:
        result[vuln["id"]] = {"status": "Passed", "url": CVEURL % vuln["id"]}
    
    if verbose:
        result[vuln["id"]]["cve"] = vuln

def showCVE(vuln):
    j = jinja2.Template("""{{ vuln["id"] }}: {{ vuln["summary"] }}
    """)
    print(j.render(vuln=vuln))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scan system for CVE affected Packages")
    parser.add_argument('--details', action="store_true", help="Verbose output")
    parser.add_argument('--id', help="Evaluate for a specific CVE")
    parser.add_argument('--show', action='store_true', help="Show CVE Details")
    args = parser.parse_args()
    
    index = genPkgIndex()
    results = {}

    if not args.id:
        logging.debug("Fetching latest vulnerabilities...")
        vulns = json.loads(requests.get("https://cve.circl.lu/api/last").content.decode('utf-8'))
        for vuln in vulns:
            if args.show:
                showCVE(vuln)
            else:
                scanCVE(index, vuln, args.verbose)
    else:
        logging.debug("Fetching Vulneratility: %s" % args.id)
        vuln = json.loads(requests.get("https://cve.circl.lu/api/cve/%s"%(args.id)).content.decode('utf-8'))
        if args.show:
            showCVE(vuln)
        else:
            scanCVE(index, vuln, args.verbose)

    if not args.show:
        pp.pprint(result)
